### ISSUE TITLE
Image not justified in preview

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#2235] opened 2019-05-02 12:04 UTC
Using the template in the editor the image shows justified to the width of the page. When viewing in preview it shows oddly inset. I would assume if it were to inset, it would at least inset centered. 

In editor:
<img width="368" alt="Screen Shot 2019-05-02 at 7 59 36 AM" src="https://user-images.githubusercontent.com/24547817/57073904-6f5e3680-6cb0-11e9-834d-8aa46fe9e0f4.png">

In Preview: 
<img width="399" alt="Screen Shot 2019-05-02 at 7 54 09 AM" src="https://user-images.githubusercontent.com/24547817/57073914-771ddb00-6cb0-11e9-9198-7b4039f155cf.png">

**Comment by kienstra** [comment] 2019-05-14 20:53
**Request For Testing**

Hi @csossi,
Could you please test this?

Please see the [steps to reproduce here](https://github.com/ampproject/amp-wp/pull/2261#issue-276081848).

This issue seems to be fixed by other PR(s), not by #2261.

**Comment by csossi** [comment] 2019-05-15 13:28
Verified in QA

Editor:
![image](https://user-images.githubusercontent.com/16945664/57779282-cd990980-76f3-11e9-82cf-52d94a77767e.png)


Front-End:
![image](https://user-images.githubusercontent.com/16945664/57779251-bbb76680-76f3-11e9-9bfc-bf3b99f318b2.png)

**Closed** 2019-06-18 04:50 UTC
Labels: AMP Stories, [AMP Stories] FE BE Discrepancy, [Type] Bug
