### ISSUE TITLE
Support WordPress installs with non-UTF-8 charsets

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#855] opened 2018-01-11 20:51 UTC
The AMP spec requires `<meta charset="utf-8">` and this is naturally problematic for sites that still use a Latin1 charset. We need to do a few things:

* For existing paired mode theme system, we'll need to use `mb_convert_encoding()` from the `get_bloginfo('charset')` to `utf-8` when reading from the DB. We'll also need to forcibly add `header( 'Content-Type: text/html; charset=utf-8' )` to override what WordPress is sending by default.
* With canonical AMP, we'll be output buffering the response and so we could convert the encoding at the time of output. We'll still need to be wary of `\AMP_DOM_Utils::get_dom_from_content()` in how it is currently assuming UTF-8 content for the input.

https://github.com/Automattic/amp-wp/blob/e60cb152a50e2ffbf5504d41aee859ad1d0e0baa/includes/class-amp-theme-support.php#L192

**Comment by westonruter** [comment] 2018-01-23 07:45
I tried to fix this as part of #888 but I failed. My abandoned patch with lots of debug code: https://gist.github.com/westonruter/04d479e809409e1f12a5944701f6f24f

The problem came down to `wptexturize()` actually. When it inserts `&#8220;` and `&#8221;` for `“` and `”` respectively, these get added converted to UTF-8 encoded chars, and then `mb_convert_encoding()` is failing to map the curly quotes between encodings, it seems:

```php
<?php
$opening_quote = '&#8220;';
$closing_quote = '&#8221;';
$output = html_entity_decode( $opening_quote . 'Hello World' . $closing_quote, ENT_QUOTES, 'UTF-8' );
$output = mb_convert_encoding( $output, 'ISO-8859-1', 'UTF-8' );
echo $output;
```

Output is:

```
00000000: 3f48 656c 6c6f 2057 6f72 6c64 3f         ?Hello World?
```

The left and right double quotes are both getting converted into `?` due to an error apparently. 

I wasn't able to prevent `DOMDocument` from converting the entities when `loadHTML`'ing either.

**Comment by schlessera** [comment] 2019-12-18 17:38
I think this should be fixed now via #3469 and the automated conversion happening inside of `Amp\AmpWP\Dom\Document`.

**Comment by csossi** [comment] 2020-02-13 17:09
Please add QA instructions, @schlessera

**Comment by schlessera** [comment] 2020-02-13 17:11
@csossi I fail to come up with an easy way to test this on the staging server, it would mean changing the default encoding of the server to test it.

@westonruter Do you have a suggestion on how we can test this in QA? Or do you think the automated tests in place are enough in this case?

**Comment by westonruter** [comment] 2020-02-13 17:23
@schlessera Yeah, I don't think there's a way to test this on staging. The only way to test would be to create a new WordPress install with a non-UTF-8 charset, populate content with non-ASCII characters, and then verify they pass through as UTF-8 without mojibake. So this would need to be developer QA, most likely.

**Comment by csossi** [comment] 2020-02-13 17:30
Moving to "Done"

**Comment by westonruter** [comment] 2020-02-13 17:32
Was it QA'd though? I'd like @kienstra perhaps to check this in a dev environment.

**Comment by csossi** [comment] 2020-02-13 17:33
Ah, ok - moving back - @kienstra - can you take a look?

**Comment by kienstra** [comment] 2020-02-13 17:34
Sure, I'll test this after the sync

**Comment by kienstra** [comment] 2020-02-14 00:52
**Testing**

Hi @westonruter,

Sorry for the delay here.

It looks like a site with a charset of `latin1` (ISO-8859-1) has HTML entities and other characters like ← that don't look the same in AMP.

Still, I don't know how meaningful this is, or how realistic these steps to reproduce are. Especially step 7 below. 

There might not be many people who set the `blog_charset` option to `ISO-8859-1`. It looks like that can't be done in the UI, at least with the current WP.

This issue doesn't occur if `get_bloginfo( 'charset' )` returns `'utf-8'` and `wp-config.php` has `define( 'DB_CHARSET', 'latin1' )`. 

It only occurs if the option was somehow changed to be `ISO-8859-1`.

Steps To Reproduce
1. `wp core download`, or whatever you use to create a new WP instance
2. Change `wp-config-sample.php` to `wp-config.php`, and enter:
```
define( 'DB_CHARSET', 'latin1' );
```
3. Make any other changes to the config needed to connect to the DB
4. `wp db create`
5. `wp core install --prompt # or however you install WP`
6. Log in to `/wp-admin`
7. `wp option update blog_charset ISO-8859-1 # latin1 charset`
8. `wp plugin install amp --activate`
9. Create a new post with a Custom HTML block
10. Enter some [HTML entities](https://www.freeformatter.com/html-entities.html) like this in the block:
```
Some A Characters:
&#194; &#195; &#196; 
Paragraph:
&#182;
Reserved (non HTML entity):
®
```
11. Save, and go to the front-end:
<img width="735" alt="characters-appear-as-expected" src="https://user-images.githubusercontent.com/4063887/74490653-d55a2a00-4e8e-11ea-9876-d04e1e52bbf5.png">

12. Select Transitional mode, and go to the AMP URL

13. Expected: the characters look the same

14. Actual: they're distorted:
<img width="581" alt="diff" src="https://user-images.githubusercontent.com/4063887/74490766-3d107500-4e8f-11ea-9f28-edaf75fa64b7.png">

**Comment by westonruter** [comment] 2020-02-14 01:03
Thank you very much. This appears to not be working.

**Comment by schlessera** [comment] 2020-02-15 08:17
Thanks for the review, @kienstra ! I'll use your steps to recreate on my end and investigate.

**Comment by schlessera** [comment] 2020-02-15 13:49
@kienstra You mention in your instruction `wp plugin install amp --activate`... Does that mean you've tested this without the PR to test included, maybe?

**Comment by schlessera** [comment] 2020-02-15 14:01
The problem seems to persist on `develop` branch, though...

**Comment by schlessera** [comment] 2020-02-15 14:24
Tracking the debugging process here.

First of all, my database now shows the following:
![Image 2020-02-15 at 3 06 39 PM](https://user-images.githubusercontent.com/83631/74589353-db721700-5004-11ea-8b35-1f3da8d72e15.png)
![Image 2020-02-15 at 3 06 51 PM](https://user-images.githubusercontent.com/83631/74589354-de6d0780-5004-11ea-8b01-1107d6e3aade.png)
![Image 2020-02-15 at 3 07 07 PM](https://user-images.githubusercontent.com/83631/74589355-e0cf6180-5004-11ea-91eb-75f1de9afe10.png)

The non-Amp version shows the correct blog charset:
![Image 2020-02-15 at 3 08 07 PM](https://user-images.githubusercontent.com/83631/74589370-0e1c0f80-5005-11ea-808f-1c99f5519a6a.png)

Within the debugger, I can see that the `adapt_encoding()` method turns this post content:

![Image 2020-02-15 at 3 14 24 PM](https://user-images.githubusercontent.com/83631/74589474-f3966600-5005-11ea-818a-b26077ba130a.png)

into this post content:

![Image 2020-02-15 at 3 14 45 PM](https://user-images.githubusercontent.com/83631/74589479-f8f3b080-5005-11ea-91dc-ace6da78af78.png)

The encoding properties in the generated DOMDocument all show "UTF-8":
![Image 2020-02-15 at 3 18 07 PM](https://user-images.githubusercontent.com/83631/74589544-6ef81780-5006-11ea-81ff-8e2e56958560.png)

The attached meta tag is correct:
![Image 2020-02-15 at 3 20 47 PM](https://user-images.githubusercontent.com/83631/74589586-c6968300-5006-11ea-8f7a-badcbf86fa51.png)


So, the logic seems to correctly identify the charset, correctly converts it into UTF-8 and correctly parses it into the DOMDocument as UTF-8.

The post content within the DOM is correct as well:
![Image 2020-02-15 at 3 22 59 PM](https://user-images.githubusercontent.com/83631/74589624-170de080-5007-11ea-8a64-e3880fb40a41.png)

Given the above, and considering the fact that the tests pass, I assume for now that all of the logic in the DOMDocument abstraction works for converting the encoding automatically, but that WordPress Core itself sees its own charset still set to `latin-1` and tries to correct that (and thus breaks the content which is now UTF-8).

I'll look into what WordPress does now.

**Comment by schlessera** [comment] 2020-02-15 14:27
Another hint that WordPress is the one messing it up:
![Image 2020-02-15 at 3 27 07 PM](https://user-images.githubusercontent.com/83631/74589696-b337e780-5007-11ea-82d9-a54372665628.png)

**Comment by schlessera** [comment] 2020-02-15 14:31
I think I found the culprit. We're not adapting the HTTP response header charset that is being sent out. So the browser converts from latin-1 to UTF-8 to correct:
![Image 2020-02-15 at 3 29 52 PM](https://user-images.githubusercontent.com/83631/74589739-322d2000-5008-11ea-8275-608d1db967d1.png)

**Comment by schlessera** [comment] 2020-02-15 15:06
Alright, enforcing the UTF-8 charset fixed it, I'll submit a PR.
![Image 2020-02-15 at 4 05 48 PM](https://user-images.githubusercontent.com/83631/74590248-14ae8500-500d-11ea-82e2-9704f2925824.png)

**Comment by schlessera** [comment] 2020-02-15 15:11
![Image 2020-02-15 at 4 09 02 PM](https://user-images.githubusercontent.com/83631/74590335-c77ee300-500d-11ea-997d-9fa2bc854d40.png)
![Image 2020-02-15 at 4 09 17 PM](https://user-images.githubusercontent.com/83631/74590336-c948a680-500d-11ea-86ca-82692aaae5fb.png)

**Closed** 2020-02-17 16:45 UTC
