### ISSUE TITLE
Error: URL validation failed to due to the absence of the expected JSON-containing AMP_VALIDATION comment after the body. This is often due to a PHP fatal error occurring. Please check your server's PHP error logs; to do this you may need to enable WP_DEBUG_LOG.

### ISSUE THREAD

**Issue by globemovingstorage** [ampproject/amp-wp#3970] opened 2019-12-19 05:55 UTC
Hi,

While validating AMP pages I'm getting the following error.

**URL validation failed to due to the absence of the expected JSON-containing AMP_VALIDATION comment after the body. This is often due to a PHP fatal error occurring. Please check your server's PHP error logs; to do this you may need to enable WP_DEBUG_LOG.**

I disabled W3-Total-Cache plugin and tried. It's validating the AMP pages.

Is there any way to solve this?

Need help with this: [https://globemoving.net/blog/
![Screenshot_2019-12-19 AMP Validated URLs ‹ Globe Moving Blog — WordPress](https://user-images.githubusercontent.com/59042334/71148631-26182280-2252-11ea-86de-3c495e5c8a0d.png)
](https://globemoving.net/blog/)

**Comment by westonruter** [comment] 2019-12-19 17:30
@globemovingstorage I believe this is a duplicate of https://github.com/ampproject/amp-wp/issues/3887. 

Please try this plugin build: [amp.zip](https://github.com/ampproject/amp-wp/files/3984815/amp.zip) (v1.5.0-alpha-20191219T172517Z-0c7ba2b4)

**Comment by westonruter** [comment] 2019-12-22 00:43
Issue also reported in [a support topic](https://wordpress.org/support/topic/url-validation-failed-message/). Fix in #3887 [verified](https://wordpress.org/support/topic/url-validation-failed-message/#post-12261527).

**Closed by westonruter** 2019-12-22 00:43 UTC
Labels: Status: Duplicate
