### ISSUE TITLE
Error on Removing Block

### ISSUE THREAD

**Issue by csossi** [ampproject/amp-wp#2321] opened 2019-05-15 13:22 UTC
- added new story
- added text block and entered text
- added image block and selected image (a large image)
- clicked image in editor and selected "Delete Block" from top toolbar
- got this:
![image](https://user-images.githubusercontent.com/16945664/57778468-210a5800-76f2-11e9-96e5-78ed8025dfa9.png)

Note that clicking "attempt recovery" takes me here, where I seem to be out of "story" mode (no add pages/ordering options):
![image](https://user-images.githubusercontent.com/16945664/57778620-734b7900-76f2-11e9-9292-29891db3494c.png)

w/console:
![image](https://user-images.githubusercontent.com/16945664/57778886-02589100-76f3-11e9-88a3-5fc559965621.png)

**Comment by swissspidy** [comment] 2019-05-16 14:13
Duplicate of #2253

**Closed** 2019-05-16 17:30 UTC
Labels: AMP-Stories, duplicate
