### ISSUE TITLE
Errors display in place of pages in the editor after preview

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#2683] opened 2019-06-25 18:37 UTC
In Chrome, created the provided story, using the provided assets (GOT). After creating multiple pages, hit "preview" without setting a featured image. 

Upon return to the editor, saw the below screen:

<img width="821" alt="Screen Shot 2019-06-25 at 10 51 59 AM" src="https://user-images.githubusercontent.com/24547817/60124008-b4ee2b80-9756-11e9-8b7d-9992613364a2.png">

**Comment by miina** [comment] 2019-06-25 18:57
Wasn't able to reproduce it by creating a few pages, then going to Preview, and then refreshing the editor.

@MackenzieHartung Do you have more specific steps for which templates were used and which blocks with which data added?

Also, the Preview opens a new tab, could you specify the steps for "returning to the editor"? Does it mean that the user opened the editor page tab again and refreshed? Did the user Save it before refreshing the page?

Thanks!

**Comment by miina** [comment] 2019-06-26 21:06
After some testing, it seems like this is most likely a duplicate of #2685 and happens for the Author role only.

Closing this as a duplicate for now and we can reopen if this issue should occur again with any other role.

**Closed by miina** 2019-06-26 21:06 UTC
Labels: AMP Stories, Needs Testing, [Status] Needs More Info, [Type] Bug
