### ISSUE TITLE
Adding animation to Author block break validation

### ISSUE THREAD

**Issue by loneken79** [ampproject/amp-wp#2376] opened 2019-05-22 09:42 UTC
Using version 1.2-Beta1

Step to reproduce :
- Make a new Story 
- add a Author bloc
- (save story draft and reload page => everything is OK)
- add animation to Author bloc (fly from bottom)
- save story and reload page 
=> Author Block validation is now broken and validation proposal is inchoherent

![melic photo_wp-admin_post php_post=38046 action=edit](https://user-images.githubusercontent.com/9193295/58164720-a360c200-7c86-11e9-93ce-b77f05b2963f.png)

**Comment by swissspidy** [comment] 2019-05-22 12:12
Hi @loneken79, thanks a lot for testing our AMP Stories integration!

While I personally have not run into this issue before, it looks like @westonruter got the same issues earlier: see #2370. And now thanks to your steps to reproduce it I can also confirm the issue.

We're going to try to solve this as soon as possible and will let you know when a fix is available.

**Comment by swissspidy** [comment] 2019-05-23 16:26
I am closing this as a duplicate of #2370, just so we can keep discussion in one place.

@loneken79 Please follow that other issue for any updates. Again, we'll try to ping you whenever we have a fix ready for testing.

**Closed by swissspidy** 2019-05-23 16:26 UTC
Labels: AMP-Stories, [Type] Bug, duplicate
