### ISSUE TITLE
[AMP Stories] Resizing doesn't properly apply to Story blocks for Title, Author, and Date

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-wp#2189] opened 2019-04-24 23:26 UTC
I added blocks for the story title, story author, and story date and then tried resizing them to cause the text to be auto-fit like the Text block, but no resizing happened:

![image](https://user-images.githubusercontent.com/134745/56700139-77fdae00-66ad-11e9-9063-6d6b15708f0e.png)

The resized blocks don't change their height in the editor, but nevertheless their heights are changed on the frontend:

![image](https://user-images.githubusercontent.com/134745/56700154-8cda4180-66ad-11e9-8e42-8a4407dad28e.png)

So either auto-fit should be applied to these blocks like it does for the Text block, or the hight of the element should be reflected in the editor as it will be on the frontend.

**Comment by swissspidy** [comment] 2019-05-15 19:36
There's #2282 for adding amp-fit-text to these blocks

**Comment by miina** [comment] 2019-05-20 13:36
Instructions for testing:
1. Add title, author, date blocks.
2. Add background color.
3. Resize the blocks.
4. Make sure that the background color fills in the full area.
5. Make sure that the font size changes according to the new resized area if "Automatically fit text to container" setting is set.
6. Make sure that the FE and editor view match.

**Comment by csossi** [comment] 2019-05-20 16:35
Very different results on front end

Editor:
![image](https://user-images.githubusercontent.com/16945664/58037534-a1b6c300-7afb-11e9-813c-ce68130d54c0.png)

Preview:
![image](https://user-images.githubusercontent.com/16945664/58037575-b004df00-7afb-11e9-8b6b-2eec78c7f313.png)

**Comment by miina** [comment] 2019-05-20 16:37
@swissspidy This might be related to #2296, assigning this to you, let me know if it seems it's not related.

**Comment by miina** [comment] 2019-05-21 16:32
Closing as ready for re-testing for QA.

**Comment by csossi** [comment] 2019-05-21 16:46
Still seeing a diff between editor and front-end re: font size/style
Editor:
![image](https://user-images.githubusercontent.com/16945664/58114706-561d1b80-7bc6-11e9-8b23-37ed5bdf7fb6.png)

FE:
![image](https://user-images.githubusercontent.com/16945664/58114736-67662800-7bc6-11e9-9b48-0f1f15553047.png)

**Comment by swissspidy** [comment] 2019-05-21 16:47
@csossi To confirm, those are: text block, author block, date block, in that order? Or is the top one a title block?

**Comment by csossi** [comment] 2019-05-21 17:10
Correct - in that order, @swissspidy

**Comment by swissspidy** [comment] 2019-05-21 20:26
I cannot seem to reproduce the font size difference.

But I noticed that the minimum block height should be improved here, see #2368.

**Comment by westonruter** [comment] 2019-05-21 21:00
Change deployed

**Comment by kienstra** [comment] 2019-05-21 22:32
**Question About Test Story**

Hi @csossi,
Thanks for testing this. Would you be able to share a link to the test story with this issue?

I tried to reproduce it with a similar story, and it looked very similar on the front-end. Maybe this was fixed in the meantime.

# [Editor](https://story-test-wordpress-amp.pantheonsite.io/wp-admin/post.php?post=1156&action=edit)

<img width="740" alt="editor-display" src="https://user-images.githubusercontent.com/4063887/58134908-faff1f00-7bed-11e9-87e4-5ab9062a412c.png">

# [Front-end](https://story-test-wordpress-amp.pantheonsite.io/stories/qa-text-bgcolour/)
<img width="894" alt="front-end-display" src="https://user-images.githubusercontent.com/4063887/58134943-24b84600-7bee-11e9-842e-5ed8238b350a.png">

**Comment by miina** [comment] 2019-05-23 09:24
@swissspidy The only difference that I could reproduce is the font size difference caused by maximum font size being 54 in the editor.

For example, adding a short text into a huge Text block causes the font size in the editor to be 54 but in the frontend to be 72 -- that seems to cause a visible difference, e.g. like Claudio has in the author block above on the screenshot. Perhaps we should increase the maximum font size in the editor a little bit and then close the issue? Thoughts?

**Comment by swissspidy** [comment] 2019-05-23 10:05
Makes sense. Let's use the same values as in the actual `amp-fit-text` component:

https://github.com/ampproject/amphtml/blob/e7a1b3ff97645ec0ec482192205134bd0735943c/extensions/amp-fit-text/0.1/amp-fit-text.js#L81-L85

**Comment by miina** [comment] 2019-05-23 19:14
@csossi Could you re-test this again?

**Closed by miina** 2019-05-23 19:14 UTC
Labels: AMP-Stories, [Type] Bug

**Comment by csossi** [comment] 2019-05-30 21:10
Verified in QA
