### ISSUE TITLE
Font size in editor appears differently than within the Preview

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#2829] opened 2019-07-17 15:52 UTC
I used a template, see screenshot below, when editing the text appears very small, but when previewing the text appears much larger.

(In Safari)

In Editor:
<img width="315" alt="Screen Shot 2019-07-17 at 11 49 07 AM" src="https://user-images.githubusercontent.com/24547817/61390706-46017f80-a889-11e9-9dd6-9922b8492250.png">

In Preview:
<img width="401" alt="Screen Shot 2019-07-17 at 11 48 57 AM" src="https://user-images.githubusercontent.com/24547817/61390724-50237e00-a889-11e9-8ee7-23d0e4ab6a81.png">

**Comment by swissspidy** [comment] 2019-07-17 16:10
Trying to reproduce this.

When I insert that template the text is sized normally in the editor, and not that small like in your screenshot. Did you resize it somehow?

**Comment by MackenzieHartung** [comment] 2019-07-17 16:57
@swissspidy no - the font size that is in the editor view (the very small one) is also how it appears in the template thumbnail:

<img width="422" alt="Screen Shot 2019-07-17 at 12 57 34 PM" src="https://user-images.githubusercontent.com/24547817/61395044-7d285e80-a892-11e9-9dca-4344c925b87a.png">

**Comment by swissspidy** [comment] 2019-07-18 12:24
Neither am I. Since #2831 fiddles with resizing and font sizes, maybe we're lucky and that helps here too.

**Comment by swissspidy** [comment] 2019-07-25 12:28
Moving out of the milestone as we were still not able to reproduce this issue.

**Comment by swissspidy** [comment] 2019-08-13 13:41
I am closing this one for now as I still cannot reproduce this issue.

We can reopen when that should change.

**Closed by swissspidy** 2019-08-13 13:41 UTC
Labels: AMP Stories, Needs Testing, [Status] Not Applicable, [Type] Bug
