### ISSUE TITLE
`amp-img` receives an unexpected inline style of `width:100vw`

### ISSUE THREAD

**Issue by felixarntz** [ampproject/amp-wp#1305] opened 2018-08-01 17:36 UTC
I'm currently working on making my site's theme AMP-compatible, and ran into this issue. I'm not quite sure whether this is caused by the AMP plugin, AMP itself or me doing something wrong.

I have a `figure` element with `wp-block-image alignfull` as classes, containing an image element, for which I have a style set `display: block; width: 100%; height: auto`. For some reason, when activating the AMP plugin (I'm aiming for native AMP, therefore I see it immediately after activating), the `amp-img` element with which it was replaced receives an inline style of `width: 100vw`, which then messes up that image's width.

Since I use Flexbox for the surrounding container, that container's width is appropriately increased by that image of 100vw width, essentially messing up the whole page layout for me. This is obviously more specific to my layout, but I'm wondering where the 100vw come from.

**Comment by westonruter** [comment] 2018-08-01 18:30
@felixarntz This may be a duplicate of https://github.com/Automattic/amp-wp/issues/1237 or https://github.com/Automattic/amp-wp/issues/1086.

There are AMP issues also opened to discuss: https://github.com/ampproject/amphtml/issues/17053 and https://github.com/ampproject/amphtml/issues/17084

**Comment by hellofromtonya** [comment] 2018-08-01 20:17
@felixarntz AMP creates an inline style for the width.  It uses a combination of the layout, sizes, and srcset (when those attributes are available).  Take a look at those 3 attributes in your project.  

As @westonruter pointed out, we do have open issues that are dependent upon resolution from the AMPHTML project issues.  From those issues, we are also seeking clarification and how the inline style is being derived.

**Comment by felixarntz** [comment] 2018-08-01 21:53
Thanks for the feedback @westonruter and @hellofromtonya! I looked into it a little further and fixed it by adjusting the `sizes` attribute of the respective image, using the `wp_calculate_image_sizes` filter.

It is still a bit less precise than before, particularly as I don't see a way to make the inline style width use % as unit (there might be a reason why this is not possible though). With the fix I made I'm satisfied now, but I'm wondering whether it would be possible to make this a more seamless process (or maybe adjust AMP if possible so that this no longer is an issue. I'll look into those issues you pointed out.

**Comment by hellofromtonya** [comment] 2018-08-01 23:53
>but I'm wondering whether it would be possible to make this a more seamless process

@felixarntz agreed.  

Once we get resolution on the two AMPHTML issues, then we can evaluate the changes they made (assuming changes are made) along with what the impact is to this plugin.

**Comment by hellofromtonya** [comment] 2018-08-09 20:54
@felixarntz Have you explored the different layout behaviors?  You can set the layout to `responsive` to get a responsive behavior.  Here are some links to checkout:

- [Demonstrating AMP layouts](https://www.ampproject.org/docs/design/amp-html-layout/layouts_demonstrated)
- [The layout attribute](https://www.ampproject.org/docs/design/responsive/control_layout#the-layout-attribute)
- [Responsive images with srcset, sizes, & heights](https://www.ampproject.org/docs/design/responsive/art_direction)

**Comment by felixarntz** [comment] 2018-08-10 11:58
@hellofromtonya I have changed all the images to `layout="responsive"`. By adjusting the `sizes` attribute I made it work for most cases. Unfortunately this is only possible to some extend because you don't know whether an image is `alignwide`, `alignfull`, half a column etc. (re @mor10, I know you have been looking into this as well).

My main issue is that the width is set as a hard `style` attribute property, which causes the layout to break easily:
* Because you can't account for all the possible layout combinations (especially in more complex themes), the hard width set might be off.
* If the width is off and you use a flex layout for the container, that container might just extend to the width of the image, making it much bigger than its intended width (for example I use `flex: 3` on the content and `flex: 1` on the sidebar).

The issue might simply require WordPress to change and allow more precise handling of the `sizes` attribute, but I'm curious for some background information why setting the width CSS property is necessary in AMP.

**Comment by hellofromtonya** [comment] 2018-08-10 12:57
@felixarntz You are correct.  AMP (not this plugin) adds the inline width style.  It uses the `sizes` attribute.  As we noted above, the AMPHTML team is looking into how the inline width is set.

Earlier this week, we merged in 2 fixes for a couple of problems we saw: wider images overflowing PR #1281 and attachment page image being stretched PR #1321. 

In the latter one, the Twenty Seventeen theme was setting the `$attr['sizes'] = '100vw';` which was stretching the image.  We fixed it by filtering `'wp_get_attachment_image_attributes'` and using `wp_get_attachment_image_sizes()` to get the sizes.  

In your theme, you can set the sizes, which you've done. 

>>The issue might simply require WordPress to change and allow more precise handling of the sizes attribute, but I'm curious for some background information why setting the width CSS property is necessary in AMP.

This is under review by the AMPHTML project team.  They are looking at the relationship between the image's dimensions, `sizes`, the inline width style, and the layout.  They are [creating a mini-project](https://github.com/ampproject/amphtml/issues/17084#issuecomment-408955537) to study and understand the behavior.

In the meantime, that outside of this plugin, we need to be setting the `sizes` attribute to a more precise handling.  I know @mor10 has given this some effort too.

**Comment by mor10** [comment] 2018-08-10 14:29
The most relevant Gutenberg ticket: https://github.com/WordPress/gutenberg/issues/6177

**Comment by westonruter** [comment] 2018-08-25 13:51
On Twenty Seventeen when uploading a square logo I see the following in non-AMP:

![image](https://user-images.githubusercontent.com/134745/44618842-7df77280-a832-11e8-9011-8aed44e04297.png)

```html
<img
	width="253" 
	height="250" 
	src="https://src.wordpress-develop.test/wp-content/uploads/2018/05/cropped-amp-brand-blue10x-1.png" 
	class="custom-logo" 
	alt="WordPress Develop" 
	itemprop="logo" 
	srcset="https://src.wordpress-develop.test/wp-content/uploads/2018/05/cropped-amp-brand-blue10x-1.png 253w, https://src.wordpress-develop.test/wp-content/uploads/2018/05/cropped-amp-brand-blue10x-1-100x100.png 100w" 
	sizes="100vw" 
/>
```

In AMP, however, this comes out as:

![image](https://user-images.githubusercontent.com/134745/44618845-8cde2500-a832-11e8-9879-99212bc3c7d6.png)

```html
<amp-img 
	width="253" 
	height="250" 
	src="https://src.wordpress-develop.test/wp-content/uploads/2018/05/cropped-amp-brand-blue10x-1.png" 
	class="custom-logo amp-wp-enforced-sizes" 
	alt="WordPress Develop" 
	itemprop="logo" 
	srcset="https://src.wordpress-develop.test/wp-content/uploads/2018/05/cropped-amp-brand-blue10x-1.png 253w, https://src.wordpress-develop.test/wp-content/uploads/2018/05/cropped-amp-brand-blue10x-1-100x100.png 100w" 
	sizes="100vw" 
	layout="intrinsic"
></amp-img>
```

@hellofromtonya Do you think this warrants a workaround like you put in place for #1321?

**Comment by westonruter** [comment] 2018-09-10 20:57
> Do you think this warrants a workaround

See https://github.com/Automattic/amp-wp/pull/1419

**Comment by westonruter** [comment] 2019-03-29 04:03
@felixarntz @hellofromtonya Would you please test #2036 which will I hope will fix issues like this going forward.

**Closed** 2019-04-04 13:40 UTC
