### ISSUE TITLE
Background 

### ISSUE THREAD

**Issue by jauyong** [ampproject/amp-wp#3919] opened 2019-12-11 19:34 UTC
## Feature description

This ticket covers background images / videos. 
Note that this is related to but different than full bleed components #3802. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by dvoytenko** [comment] 2019-12-16 17:26
Duplicate of https://github.com/ampproject/amp-wp/issues/3936

**Closed by dvoytenko** 2019-12-16 17:26 UTC
Labels: Stories
