### ISSUE TITLE
Right Click context Menu doesn't open for meta blocks when right-clicking on text

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#3416] opened 2019-10-02 12:18 UTC
## Bug Description

The context menu doesn't open for meta blocks when right-clicking on text

## Expected Behaviour

Expected result: The custom context menu should open.

## Steps to reproduce

- Add a meta block (e.g. Author or Title)
- Right-click in the center of the block where there is text.
- The default menu opens.

## Screenshots

![right-click](https://user-images.githubusercontent.com/3294597/66043418-5f78a600-e51f-11e9-8886-ee5f65cef66f.gif)

## Additional context

 - WordPress version: 5.3
 - Plugin version: `develop`
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* After right-clicking anywhere within a meta block, the context menu should open. 
   * This includes right-clicking on text within a meta block
* After right-clicking on highlighted text in a meta block, the default context menu should open

## Implementation brief

* By default, disable text selection for meta blocks and only enable when block is in "edit mode".
* Add logic to enable edit mode once block is selected and then clicked again.
* See [branch for PoC implementation](https://github.com/ampproject/amp-wp/compare/fix/3416-context-meta-block?expand=1) and [comment below for demo](https://github.com/ampproject/amp-wp/issues/3416#issuecomment-548067558).

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by spacedmonkey** [comment] 2019-10-02 12:40
I disagree this is an issue. For those who use screen readers, when text is highlights, you would want the built in context menu to display, so you can pick the speech option. This seems like the correct behaviour to me.

**Comment by miina** [comment] 2019-10-02 12:48
I agree that if the text is highlighted then the default context menu should display, however, in this case it opens the default context menu even if it's not highlighted at first.

Maybe you're right and it's how it should work, it's just unexpected that in case the block is full of text then it doesn't open the custom menu and selects the text instead + then opens the default menu. It feels like inconsistent behavior.

Thoughts?

**Comment by swissspidy** [comment] 2019-10-02 12:56
So basically this needs the same double click solution as the text block?

**Comment by miina** [comment] 2019-10-02 12:59
Possibly, yes. If that's the expected behavior.
In this case, the double click here would allow selecting the text or already select some text (since the text itself can't be changed).

**Comment by swissspidy** [comment] 2019-10-02 13:05
> (since the text itself can't be changed).

FWIW at some point we'd want to enable that, at least for the title block.

**Comment by spacedmonkey** [comment] 2019-10-27 14:36
For those that use a screen reader, like I do, text should be highlightable so a user a can highlight text and select Speech, to get your computer to read the text to you. The built in context menu has lots of users to accessibility software. Removing it when text is highlighted could be problematic here.

**Comment by miina** [comment] 2019-10-28 09:38
> Removing it when text is highlighted could be problematic here.

There is no suggestion to remove the default context menu when the text is highlighted. It's currently specifically done so that if some text is highlighted, the custom context menu would _not_ be used and the default would appear:
https://github.com/ampproject/amp-wp/blob/41cda10ee6a27e5a37686a8682c2fa138118f198/assets/src/stories-editor/components/higher-order/with-context-menu.js#L32-L37

Also, the text would remain highlightable on double click, as it is in case of a Text block.

Could you clarify the worry here considering that the text can be highlighted and the default context menu used if the text is highlighted?

**Comment by spacedmonkey** [comment] 2019-10-28 11:37
As long a the default context menu shows when text is still highlighted, then I am happy.

**Comment by jauyong** [comment] 2019-10-30 17:35
Hey all, I've added some AC based on the discussion here and I'll move to the IB column. 
CC: @jasti

**Comment by barklund** [comment] 2019-10-30 19:06
Attempted fix in [this branch](https://github.com/ampproject/amp-wp/compare/fix/3416-context-meta-block?expand=1) with the result as can be seen below in GIF:
![result](https://user-images.githubusercontent.com/637548/67889705-b3c67400-fb25-11e9-9d26-90cb3275a3c5.gif)

As can be seen the result is:

- Element can still be dragged
- Text can still be selected
- Custom context menu can be invoked if the element is not already selected
- Built-in context menu will be invoked if right-clicking text after the element is selected.

Is this how we do it, @miina, @swissspidy, @spacedmonkey?

**Comment by miina** [comment] 2019-10-30 22:53
Yep, it looks like that's how it works for the Text block, so this behavior does make it consistent for all the blocks that contain text. I'm wondering, however, if the default context menu should appear only if the text is already selected, e.g. if a block is selected but the text hasn't been selected, then open the custom context menu, and if text is selected, then open the default context menu? Currently, the block needs unselecting first. Thoughts?

**Comment by barklund** [comment] 2019-10-31 15:10
> I'm wondering, however, if the default context menu should appear only if the text is already selected, e.g. if a block is selected but the text hasn't been selected, then open the custom context menu, and if text is selected, then open the default context menu? Currently, the block needs unselecting first. Thoughts?

The issue is, the mere action of pressing the right click mouse button (in chrome at least) while over a word automatically selects that word in question (try it right here on Github) if the text is selectable.

We can't both have the text selectable and not allow right-click on a word to select the word and bring up the selection context menu.

I'll advance this ticket to the execution board. The above is a future concern.

**Comment by miina** [comment] 2019-10-31 16:34
Sounds good, thanks!

**Comment by csossi** [comment] 2019-11-12 16:03
Verified in QA

**Comment by westonruter** [comment] 2019-11-14 19:03
Closing because part of impending 1.4.1 release.

**Closed by westonruter** 2019-11-14 19:03 UTC
Labels: AMP Stories, Needs Testing, Size: XS, Type: Bug
