### ISSUE TITLE
How to redefine featured image sizes?

### ISSUE THREAD

**Issue by Ipstenu** [ampproject/amp-wp#2684] opened 2019-06-25 19:39 UTC
In non-story custom posts, I sometimes use vertical featured images. This means that the crop for 1200x600 is incorrect and should use 9x16 instead of 16x9 as the math (1200x2134)

Is there any way I can override that for selected post types? Otherwise, can I disable the prompt to crop so my editors stop making images that don't work right from the NON-amp layouts?

**Comment by swissspidy** [comment] 2019-06-26 09:37
Thanks a lot for raising this Mika!

The image cropping is based on a requirement by Search Console to have [big enough images](https://developers.google.com/search/docs/data-types/article) for AMP pages.

Looks like we need to do better testing for vertical images. So if we would fix this to crop an image to something like `1200x2134`, would that already work for you?

**Comment by Ipstenu** [comment] 2019-06-26 15:50
I know the recommendation, it's just SUPER overly aggressive and not context aware which is resulting in breaking the design of my site. And I'm sure I'm not the only person who faces this issue :(

> So if we would fix this to crop an image to something like 1200x2134, would that already work for you?

That would work. We're uploading the right image sizes, but there's no way to tell the cropper to chill out and treat vertical as okay.

That said ... with the default assumption being 16x9, when the real request is this:

> Images should be at least 1200 pixels wide.

That's just really annoying for everyone who wants to customize height. At least until we get to story, and then of course I have to sort out how to tell the plugin "This story has Portrait, this one has Landscape"

**Comment by swissspidy** [comment] 2019-06-26 16:12
Thanks for clarification! I am sure we can find a good solution here.

**Comment by swissspidy** [comment] 2019-06-27 13:03
@kienstra Could you have a look at the cropping issues with vertical images?

**Comment by Ipstenu** [comment] 2019-06-27 16:34
Speaking of overly aggressive, I've noticed that if I have an image that's exactly 1200x645 _sometimes_ the tool tells me it's too small. I suspect it's a rounding error somewhere in one app or another, but there may need to be some mathematical wiggle room to account for that.

**Comment by kienstra** [comment] 2019-06-27 17:15
>@kienstra Could you have a look at the cropping issues with vertical images?

Hi @swissspidy, 
Sure, though it might be tomorrow before I could start on this, if that's alright.

**Comment by kienstra** [comment] 2019-07-01 03:56
**Thanks!**
*Question about featured image dimensions*

Hi @Ipstenu,
Thanks for bringing this up. You might have seen this already, but the newly-opened PR #2711 begins the work of adding support for portrait featured images.

>Speaking of overly aggressive, I've noticed that if I have an image that's exactly 1200x645 sometimes the tool tells me it's too small. I suspect it's a rounding error somewhere in one app or another, but there may need to be some mathematical wiggle room to account for that.

That must be confusing to have the tool *sometimes* notify you that it's too small 😄 

Did you mean `1200 x 675` instead of `1200 x 645`? 

`1200 x 675` is the expected size for featured images. But even then, that would probably be a bug if it only *sometimes* notified of the wrong size.

**Comment by Ipstenu** [comment] 2019-07-01 15:51
Sorry yes I meant 675. I had an image that my Mac said was 1200x675 and so did WP but it also said I needed to resize it. I may have a screenshot because it amused me.

--
Mika A. Epstein | @ipstenu
https://halfelf.org | https://ipstenu.org

**Comment by kienstra** [comment] 2019-07-01 21:11
Hi @Ipstenu,
Thanks, that must have been strange seeing a notice that the `1200 x 675` image was too small.

Do you remember if the notice was in:

1. The Gutenberg 'Inspector' panel:
<img width="581" alt="inspector-panel" src="https://user-images.githubusercontent.com/4063887/60466943-b9b15480-9c1a-11e9-90ca-1f8f6f73b099.png">

2. The Media Library, on clicking 'Set featured image' in Gutenberg:
<img width="791" alt="notice-media-library" src="https://user-images.githubusercontent.com/4063887/60466927-b3bb7380-9c1a-11e9-9495-941943026aa2.png">

...or maybe both 😄 

Thanks, Mika.

**Comment by Ipstenu** [comment] 2019-07-01 21:17
Both!

**Comment by kienstra** [comment] 2019-07-01 21:20
Thanks, I'll work on reproducing both.

**Comment by kienstra** [comment] 2019-07-02 03:47
**Request To Test**

Hi @swissspidy,
Could you please test setting `1200 x 675` featured images, to see if they cause a notice to appear?

I couldn't quite reproduce this. Though I did [see an issue](https://github.com/ampproject/amp-wp/pull/2711#issuecomment-507504228) where the notice appeared for a second in the Media Library, then disappeared.

**Steps To Test**

1. Create a new post (not an AMP Story)

2. Click 'Set featured image'

3. Upload a `1200 x 675` image, like [this](http://lorempixel.com/1200/675/technics/) or [this](https://ipsumimage.appspot.com/1200x675)

4. Expected: there's no notice in the Media Library:

<img width="780" alt="should-be-no-notice" src="https://user-images.githubusercontent.com/4063887/60481006-542c8a80-9c51-11e9-9973-d7f572139fc4.png">

5. In the Media Library, click 'Select'

6. Expected: there's no notice in the Inspector about a wrong featured image size:
<img width="622" alt="featured-image-size-inspector" src="https://user-images.githubusercontent.com/4063887/60481115-ad94b980-9c51-11e9-83f9-efabfdab7ef6.png">

7. Repeat all of these steps, except in step 3, don't upload a new image. Select a `1200 x 675` image that you already uploaded.

Thanks, Pascal!

**Comment by swissspidy** [comment] 2019-07-02 09:46
@Ipstenu Here's an updated build of the plugin that contains Ryan's fix: 
[amp.zip](https://github.com/ampproject/amp-wp/files/3349412/amp.zip)

Could you please test that and let us know whether it works as expected or if we missed something? Thanks!

**Comment by Ipstenu** [comment] 2019-07-05 16:05
Testing that it doesn't tell me that a 683x1024 image is the wrong size, nor does it prompt for cropping. That doesn't seem correct?

**Comment by kienstra** [comment] 2019-07-09 22:23
Hi @Ipstenu,
Right now, the expected behavior in uploading a [683 x 1024 image](http://lorempixel.com/683/1024/technics/) as the featured image to a post (not AMP Story) would be that there is a notice:

>The selected image is too small (683 by 1024 pixels). It should have a size of at least 1200 by 675 pixels.

...and it won't prompt for cropping.

<img width="860" alt="notice-post" src="https://user-images.githubusercontent.com/4063887/60927029-fcec7280-a26d-11e9-93c5-28d415dca2b7.png">

As [detailed above](https://github.com/ampproject/amp-wp/issues/2684#issuecomment-507506874), on uploading a `1200 x 675` image as the featured image to a post (not an AMP Story), like [this](http://lorempixel.com/1200/675/technics/) or [this](https://ipsumimage.appspot.com/1200x675), there should be no notice of the size being wrong, nor a prompt for cropping,

**Comment by Ipstenu** [comment] 2019-07-10 00:21
Ah! Okay then :) Then it works.

**Comment by kienstra** [comment] 2019-07-10 00:23
Sounds good, thanks for your patience and for testing this!

**Comment by westonruter** [comment] 2019-07-10 20:28
@kienstra Now that #2711 has been merged, is there anything left for this? Or should it be closed and move to Ready for QA?

**Comment by kienstra** [comment] 2019-07-10 20:38
Hi @westonruter,
You're right, I'll move this to 'Ready for QA.'

**Comment by kienstra** [comment] 2019-07-10 20:40
**Request For Testing**

Hi @csossi,
Could you please test this, with the [steps above](https://github.com/ampproject/amp-wp/issues/2684#issuecomment-507506874)?

Thanks!

**Comment by csossi** [comment] 2019-07-11 19:09
Verified in QA

**Comment by kienstra** [comment] 2019-07-11 19:12
Thanks, @csossi!

**Comment by Ipstenu** [comment] 2019-08-29 21:28
So this came back with the last update.

The issue is back to "I'm uploading an image that is VERTICAL and meets the parameters of what Google wants, but AMP is prompting me to crop it."

We're not ready for stories yet, so if there's just a way for me to say "Do not prompt to crop for these." that would be the easiest solution for us :(

**Comment by westonruter** [comment] 2019-08-29 22:02
I think the reason cropping is being offered is this line in the structured data [`image` docs](https://developers.google.com/search/docs/data-types/article#article_types):

> Images should be at least 1200 pixels wide. […] For best results, provide multiple high-resolution images (minimum of 800,000 pixels when multiplying width and height) with the following aspect ratios: 16x9, 4x3, and 1x1.

As indicated, this is for “best results” and it is not required. There are [different requirements](https://amp.dev/documentation/components/amp-story/?referrer=ampproject.org#poster-guidelines-(for-poster-portrait-src,-poster-landscape-src,-and-poster-square-src)) for stories, which are more strict (e.g. specific aspect ratios).

As it stands right now, the non-story cropper is forcing a 16x9 aspect ratio, I presume, because 4x3 and 1x1 can be derived from it by center-cropping (which is not foolproof).

It seems to me that we should just disable the cropping dialog altogether for non-story posts.

**Comment by Ipstenu** [comment] 2019-08-29 22:05
I like having the notice "Hey this image may be too small" but sadly I'm having the user drama of an editor NOT realizing that cropping our images that should be vertical will result in a mucked up non-AMP display. 

FWIW I think even with Stories, this force-crop (even though it's skippable) is going to confuse users who aren't up to speed on what this is all about. The intention is there, but the implementation doesn't come with enough education to the end-user. Imagine explaining this to a newbie :)

**Comment by kienstra** [comment] 2019-08-31 02:11
**Question About Notices In non-Story Block Editor**

Hi @westonruter,

>It seems to me that we should just disable the cropping dialog altogether for non-story posts.

Sounds good. We should still keep the notices for small featured image on non-Story posts, even while removing cropping, right?

Removing the notices and cropping would be a [pretty simple change](https://github.com/ampproject/amp-wp/blob/8b21d12a1ba4fa6a93abafbaa2a5a3c1488fe456/assets/src/block-editor/index.js#L40), while keeping the notices would be more complex. But it seems like the notices would still be appropriate 😄 

<img width="861" alt="post-block-editor" src="https://user-images.githubusercontent.com/4063887/64058000-52f0de80-cb6a-11e9-9340-f4fb3f62ba45.png">

<img width="628" alt="post-be" src="https://user-images.githubusercontent.com/4063887/64058004-56846580-cb6a-11e9-91e7-1c033bd4b3ae.png">

Thanks, and have a great weekend!

**Comment by westonruter** [comment] 2019-08-31 03:06
Yes, I think the notice should remain but just remove the cropping.

**Comment by kienstra** [comment] 2019-08-31 07:22
Sounds good, thanks.

**Comment by kienstra** [comment] 2019-09-11 06:44
**Steps To Test**
(For when this makes it to testing)

1. Create a post (not an AMP Story)
2. Click 'Set featured image'
3. Select or upload an image [smaller than 1200 x 675](http://lorempixel.com/600/600/technics/)
4. Expected: there is a notice at the bottom of the Media Library of the small image size
5. Expected: on clicking 'Select,' there should be no cropping suggested

<img width="1222" alt="no-cropping-notice" src="https://user-images.githubusercontent.com/4063887/64674015-50796900-d435-11e9-91ab-9fcf854aca61.png">

**Comment by kienstra** [comment] 2019-09-11 06:45
If it would help, I could create a screencast for this. But it's mainly removing a feature (cropping).

**Comment by westonruter** [comment] 2019-09-11 21:56
@Ipstenu Here's a build for testing: https://github.com/ampproject/amp-wp/pull/3177#issuecomment-530581564

I believe that the current state of the PR addresses your concerns. Would you test?

**Closed** 2019-09-13 18:01 UTC
Labels: Media, Sprint 10, [Integration] Gutenberg, [Priority] Medium, [Size] S, [Type] Bug

**Comment by csossi** [comment] 2019-09-18 15:47
Verified in QA
