### ISSUE TITLE
AMP_Gallery_Embed_Handler styles circumvent sanitizer

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-wp#4156] opened 2020-01-21 17:55 UTC
## Bug Description

The `AMP_Gallery_Embed_Handler` [adds an action to the `wp_print_styles` hook](https://github.com/ampproject/amp-wp/blob/1.4.2/includes/embeds/class-amp-gallery-embed.php#L20) to print a custom style rule:
```css
<style>
	.wp-block-gallery.is-cropped .blocks-gallery-item amp-img > img {
		object-fit: cover;
	}
</style>
```

As this runs within the sanitizer, it seems to print the styles at the wrong time.

On the following site, you can see that it prints the CSS after the `<style amp-custom></style>`, and thus causes an AMP validation error:
[https://www.anduril.band/?amp](https://www.anduril.band/?amp)

## Expected Behaviour

The AMP plugin should not circumvent its own sanitization.

## Steps to reproduce

TBD

## Screenshots

![Image 2020-01-21 at 4 32 56 PM](https://user-images.githubusercontent.com/83631/72829498-2eafae80-3c7f-11ea-98f6-3c841f7a17a5.png)

![Image 2020-01-21 at 4 34 44 PM](https://user-images.githubusercontent.com/83631/72829503-31aa9f00-3c7f-11ea-80a2-8d758c8185c3.png)

![Image 2020-01-21 at 4 34 49 PM](https://user-images.githubusercontent.com/83631/72829508-34a58f80-3c7f-11ea-9655-4d8f789de543.png)

cc @TungstenE2

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment] 2020-01-21 18:24
This has come up before. See https://github.com/ampproject/amp-wp/issues/1780

I thought it was due to the NextGEN Gallery plugin which also was doing output buffering: https://github.com/ampproject/amp-wp/issues/1780#issuecomment-454505571

**Comment by TungstenE2** [comment] 2020-01-29 12:15
any update on this as #1780 is already closed and the issue is still existing.

Since I installed the plugin I get error messages by Google Search Console.

![search-console](https://user-images.githubusercontent.com/39955685/73355913-70e97900-4299-11ea-9ce2-5777e8beab88.PNG)

**Comment by westonruter** [comment] 2020-01-29 20:51
@TungstenE2 I'm confused as to why this is happening. Styles printed at the `wp_print_styles` action should be part of the entire page's output buffer which would then get processed by the style sanitizer. This is not happening for you, for some reason. What plugins do you have active?

**Comment by TungstenE2** [comment] 2020-01-30 06:49
There are 17 active plugins:


AMP
Version 1.4.2 

Cryptex - E-Mail Address Protection auswählen
Version 7.1 | Von Andi Dittrich 

Dashboard Directory Size 
Version 1.6.0 | Von Pete Nelson (@GunGeekATX) | 
	
Disable Feeds
Version 1.4.4 
	
Disable REST API
Version 1.5 | Von Dave McHale 
	
Duplicator
Version 1.3.24


Easy Updates Manager
Version 9.0.1 

EWWW Image Optimizer
Version 5.1.4 | Von Exactly WWW 
	
NextGEN Gallery
Version 3.2.23 | Von Imagely 

Recent Posts Widget With Thumbnails
Version 6.7.0 | Von Martin Stehle 

WordPress Dashboard Widget zeigt die wichtigsten Seiten-Infos.
Version 1.1 | Von Rami Yushuvaev 
	
Self-Hosted Google Fonts
Version 1.0.1 | Von asadkn 
	
Wordfence Security - Anti-virus, Firewall and Malware Scan
Version 7.4.5 | Von Wordfence |
	
WP Statistics
Version 12.6.12 | Von VeronaLabs 
	
WP YouTube Lyte
Version 1.7.11 | Von Frank Goossens (futtta) 
	
WP-Dateimanager
Version 5.7 | Von mndpsingh287 
	
Yoast SEO
Version 12.9.1 | Von Team Yoast

**Comment by westonruter** [comment] 2020-01-30 06:58
I see you are using NextGEN Gallery. This was the same cause for the failure in #1780.

If you deactivate that plugin, does the page then validate via the [AMP validator](https://validate.amp.dev)?

I made a workaround plugin to try to fix what NextGEN Gallery is doing here. It's not pretty but it works: https://github.com/ampproject/amp-wp/issues/1780#issuecomment-454505571

**Comment by TungstenE2** [comment] 2020-01-30 07:13
validate.amp.dev is not available.

When will you release a final fixed plugin? I assume many people are facing this issue.
Should the issue be fixed in Nextgen Gallery or in AMP plugin?

**Comment by westonruter** [comment] 2020-01-30 07:19
Sorry, the correct URL is https://validator.amp.dev/

The fix is needed for NextGEN not the AMP plugin, I believe. My [above workaround plugin](https://gist.github.com/westonruter/99b1ca0d593f44888401a396d991e3a6) is one option. 

You can alternatively try adding this to your `wp-config.php` (which my workaround plugin does conditionally):

```php
define( 'NGG_DISABLE_RESOURCE_MANAGER', true );
```

**Comment by TungstenE2** [comment] 2020-01-30 07:57
Validation Status is failed, even with deactivated NextGEN Gallery.
https://validator.amp.dev/#url=https%3A%2F%2Fanduril.band

How about a settings option instead of aditional workaround plugin?
Did you inform NextGEN Gallery developers?

Also I have AMP error index of 356. What does this mean?

![amp-errors](https://user-images.githubusercontent.com/39955685/73430468-73ea7500-433e-11ea-8575-757d242b2e32.PNG)

**Comment by TungstenE2** [comment] 2020-01-30 11:53
here is another page from me, where I use the AMP plugin and the validator is failing. But on this page no NextGEN Gallery is installed. 

https://validator.amp.dev/#url=https%3A%2F%2Fwww.fahrschule-poleposition.de%2F

**Comment by westonruter** [comment] 2020-01-30 15:15
> Validation Status is failed, even with deactivated NextGEN Gallery.
https://validator.amp.dev/#url=https%3A%2F%2Fanduril.band

Actually, you tried validating the non-AMP version. Validating the AMP version shows now that it is valid: https://validator.amp.dev/#url=https%3A%2F%2Fanduril.band%2F%3Famp

When in Transitional mode, make sure you check the AMP URL which has `?amp` in it.

**Comment by TungstenE2** [comment] 2020-01-30 16:04
uups, I thought the validator would catch the correct URL of the domain for AMP.

**Comment by westonruter** [comment] 2020-01-30 18:15
The other URL is also validating: https://validator.amp.dev/#url=https%3A%2F%2Fwww.fahrschule-poleposition.de%2F%3Famp

> Also I have AMP error index of 356. What does this mean?

For these, you should look click on right-most column which indicates the URLs that the errors occur on. Open the Validated URL screen for one single URL that has the error. And then share a screenshot of that validation error expanded. This will include the full details of the error, including where it came from.

**Comment by TungstenE2** [comment] 2020-01-31 07:03
seems like I have 2 repeating issues: 

invalid markup <script> in head and body

may be related to Wordfence Plugin?
var WFAJAXWatcherVars = {"nonce":"cca334a752"};

![AMP2](https://user-images.githubusercontent.com/39955685/73518879-c6d83100-43ff-11ea-8e98-600f98850b11.PNG)
![AMP3](https://user-images.githubusercontent.com/39955685/73518886-cc357b80-43ff-11ea-92bf-a77ef4783dc2.PNG)

**Comment by westonruter** [comment] 2020-01-31 18:08
Please go to “Validated URLs” and expand the validation errors in that contest. When an error is shown in the context of the URL it occurs on it should then indicate which theme/plugin is responsible for adding it.

From looking at the Wordfence plugin, I can indeed see the script with `WFAJAXWatcherVars` is coming from that plugin. You can suppress the validation error from being reported (in other words, automatically marking it as “Removed”), with this code:

```php
add_filter(
	'amp_validation_error_sanitized',
	function ( $sanitized, $error ) {
		if ( isset( $error['node_name'], $error['text'] ) && 'script' === $error['node_name'] && false !== strpos( $error['text'], 'WFAJAXWatcherVars' ) ) {
			$sanitized = true;
		}
		return $sanitized;
	},
	10,
	2
);
```

The other error is coming from the Cryptex plugin. And you can adapt the above code to also automatically remove the invalid `script` on AMP pages.

In any case, when using plugins that are not explicitly AMP-compatible it is normal to see validation errors like these. Since custom scripts are not allowed in AMP (in the traditional way), the AMP plugin removes them. This leaves the page behaving as if the user had JavaScript turned off in the browser. So as long as plugins have an acceptable fallback experience for when JS is turned off, this will default become the AMP experience. The AMP plugin even unwraps `noscript` elements to that their contents become the AMP version by default.

**Closed by westonruter** 2020-01-31 18:08 UTC
Labels: CSS, Group: Embeds, Sanitizers
