### ISSUE TITLE
Facebook Sanitizer Returning False Positives

### ISSUE THREAD

**Issue by sethta** [ampproject/amp-wp#1955] opened 2019-03-12 20:34 UTC
The current implementation is taking any tag with a `data-href` attribute and a class name and will auto convert those to an `amp-facebook` tag.

We have a plugin that contains a div with a `data-href` tag and it has a class attribute. Because that passes the first check from AMP in the `get_embed_type()` method of `AMP_Facebook_Embed_Handler`, there is no way to get around this.

The current check is to see if there's a `fb-post` class, and then a `fb-video` class. Then it falls back to check for a video class a second time, and if that fails, returns `post`.

The only current solution is to change the `data-href` attribute to something else, but as that's a logical name for a data attribute, it may be affecting more than just us.

**Comment by westonruter** [comment] 2019-03-12 20:42
@sethta Is this a duplicate of https://github.com/ampproject/amp-wp/issues/1259#issuecomment-404280943?

**Comment by sethta** [comment] 2019-03-12 20:51
I don't believe so. I read that before and it looks like it was referring to correctly categorizing Facebook post/page/videos into the correct tag.

This is regarding a plugin that has nothing do do with Facebook. We just are using a `data-href` attribute in the markup, so AMP is converting it to a facebook tag, which removes the tag completely.

I'm working on a PR for our plugin to use `data-list-href` instead, but worry that others may come across the same issue.

**Comment by westonruter** [comment] 2019-03-12 20:59
I think fixing https://github.com/ampproject/amp-wp/issues/1259#issuecomment-404280943 will also end up fixing the problem you have identified here. The issue is that the it is naïvely only looking at the `data-href` attribute and then after checking for `fb-post` and `fb-video` it makes this major assumption which is incorrect:

https://github.com/ampproject/amp-wp/blob/024e450798c35a89c3390c410ab42522a924f712/includes/embeds/class-amp-facebook-embed.php#L111

It should be returning `null` here, or rather that line should be removed entirely.

**Comment by sethta** [comment] 2019-03-12 21:04
I agree. That line seemed redundant, and is what forced the change to the `amp-facebook` tag.

Thank you.

**Comment by westonruter** [comment] 2019-03-12 21:21
@sethta I'm working on a PR. Would you test?

**Comment by sethta** [comment] 2019-03-12 21:28
Sure

**Comment by sethta** [comment] 2019-03-12 21:36
I've got to head out, but I can confirm that by commenting out that line, our code runs correctly and is not changed to `amp-facebook` tags on AMP

**Closed** 2019-03-16 16:57 UTC
Labels: [Type] Bug
