### ISSUE TITLE
Character problem due to Js error

### ISSUE THREAD

**Issue by tryazi** [ampproject/amp-wp#1806] opened 2019-01-11 16:28 UTC
Hello there
I don't use my homepage as an amp. Native always gives a character error. This only applies to the home page.

No problem if I chose Paried. I am using Livesearch and this is necessary for me

![karakter](https://user-images.githubusercontent.com/45657726/51046423-0fdffc00-15d7-11e9-90b8-5081a8e70b70.png)

https://www.odevbul.org

**Comment by westonruter** [comment] 2019-01-11 17:54
Is this not a duplicate of what you opened in #1778? 

Looking at the network log, I can see that the auto-completions are being populated via XHRs with URLs like: https://www.odevbul.org/?livesearch=used&s=test

If you look at that URL, you'll see that this URL unexpectedly has the `amp` attribute on the `html` element.

**Comment by tryazi** [comment] 2019-01-11 17:58
I'm sorry I completely forgot

**Closed** 2019-01-11 17:59 UTC
