### ISSUE TITLE
Font Picker 

### ISSUE THREAD

**Issue by jauyong** [ampproject/amp-wp#3916] opened 2019-12-11 19:28 UTC
## Feature description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by swissspidy** [comment] 2019-12-16 09:44
@jauyong Duplicate of #3759?

**Comment by jauyong** [comment] 2019-12-16 16:20
@swissspidy I'll delete this. I think was supposed to be for #3917

**Closed** 2019-12-16 16:21 UTC
