### ISSUE TITLE
Layering of blocks makes actioning on functions challenging

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#2231] opened 2019-05-02 10:47 UTC
When creating a story I am adding multiple blocks to a page. They appear layered on on another, and create frustration/challenges in trying to access the blocks functions.

<img width="435" alt="Screen Shot 2019-05-02 at 5 21 23 AM" src="https://user-images.githubusercontent.com/24547817/57070602-fb1e9580-6ca5-11e9-9061-5ae8514cda14.png">

Date is behind text block:
<img width="761" alt="Screen Shot 2019-05-02 at 6 17 37 AM" src="https://user-images.githubusercontent.com/24547817/57070603-fb1e9580-6ca5-11e9-9d4c-b43f13c030c2.png">

**Comment by miina** [comment] 2019-05-02 11:07
I encountered a similar issue when using just two blocks, to reproduce:
- Add an image block, add an image which covers the full width.
- Add a list block. Try to drag it.

Here the list block is selected and the drag-drop icon shows:
![Screen Shot 2019-05-02 at 12 46 51 PM](https://user-images.githubusercontent.com/3294597/57071536-0809ac00-6cdb-11e9-9db4-25db94cf5cb6.png)

When I try to drag the block by moving the cursor to the dragging icon then the drag-drop icon disappears since the Image block is hovered instead making it impossible to drag the newly created list block:
![Screen Shot 2019-05-02 at 12 47 01 PM](https://user-images.githubusercontent.com/3294597/57071559-1d7ed600-6cdb-11e9-99b0-1a86ec388e19.png)

**Comment by swissspidy** [comment] 2019-05-06 16:25
Related: #2181, #2179, #2244

**Comment by miina** [comment] 2019-05-09 07:57
As suggested by @swissspidy over the call on Monday, I tested this again and it seems to be much better now, I couldn't replicate the issue I had before.

Suggesting that this could be closed after #2181 gets implemented.

**Comment by swissspidy** [comment] 2019-05-14 22:21
Given that we also have #1974 already, I'm inclined to close this as "no action needed" even before #2181 is done. Thoughts?

**Comment by miina** [comment] 2019-05-15 08:43
Sounds good to me, we can close the ticket.

**Closed by miina** 2019-05-15 08:43 UTC
Labels: AMP-Stories, [Type] Bug
