### ISSUE TITLE
Add toggle to enable supports-landscape for stories

### ISSUE THREAD

**Issue by jdelia** [ampproject/amp-wp#2448] opened 2019-05-28 18:59 UTC
It would be very useful to have a toggle either in the plugin settings or in an individual story setting to enable `support-landscapes` in the `<amp-story` HTML output. This would add progressive enhancement easily for users who want to provide an immersive user experience on the desktop. 

Right now we have to edit the plugin to add `supports-landscape` to the HTML output in the `single-amp_story.php` file.

**Comment by westonruter** [comment] 2019-05-28 19:00
Thank you for the suggestion. You're right! I think this is a duplicate of #2409.

**Closed by westonruter** 2019-05-28 19:00 UTC
Labels: AMP-Stories
