### ISSUE TITLE
Stories loading and design time issue

### ISSUE THREAD

**Issue by dhruva205** [ampproject/amp-wp#2477] opened 2019-05-31 10:21 UTC
While designing my stories, this graphic hiding took place when i tried to put an image on the story(a separate image , not the background) . When tried to align and resize the image frame , the screen turned like this( screenshot)
![s152](https://user-images.githubusercontent.com/38184542/58698976-030f4980-83ba-11e9-994f-aa759164a3de.jpg)

Apart from this, when i completed the story and view it , it ended up like this..
![s153](https://user-images.githubusercontent.com/38184542/58699087-51244d00-83ba-11e9-9d7b-0c15a008ed67.jpg)

Experimenting with more posts, i also found that some such errors occurs if i re-arrange the story slides in the editor.... i am attaching the images, one is after i made the story, and second is when i shuffled the pages and third one will be after i just shuffled the pages of story from the editor and result was that no text appeared this time, if i add more of the elements to my pages and then shuffle them, the changes and errors are likewise.....
![s154](https://user-images.githubusercontent.com/38184542/58699689-b3318200-83bb-11e9-9fea-cca98e07f652.jpg)
![s157](https://user-images.githubusercontent.com/38184542/58699701-bc225380-83bb-11e9-964f-6703cf888b9f.jpg)
![s155](https://user-images.githubusercontent.com/38184542/58699714-c6dce880-83bb-11e9-9865-5363c6882d2d.png)

**Comment by westonruter** [comment] 2019-05-31 18:57
> When tried to align and resize the image frame , the screen turned like this( screenshot)

I've seen this happen before in the context of the editor encountering a fatal error. Can you open your browser's JavaScript console to look for any such errors?

**Comment by dhruva205** [comment] 2019-05-31 20:42
Well i will do that part and will inform, for now i noticed a thing which i want to share.....
@westonruter 
as in image
https://user-images.githubusercontent.com/38184542/58699087-51244d00-83ba-11e9-9d7b-0c15a008ed67.jpg

that type of error occurred when i added a new slide in the apm story editor side
by using the shortcut **ctrl+shift+d**   with this, the current selected page gets duplicated , after that , when i viewed the story again that above error occurred...
And when i removed that duplicated section... it was fixed, story displayed normally!

**Comment by swissspidy** [comment] 2019-06-03 10:17
Thanks for your report @dhruva205! I will try to reproduce this issues on my environment. Based on the screenshots I couldn't tell what would cause something like that.

As for the image bug, I thought I had fixed that with #2119. But maybe something has changed now. Will have a look at that too.

**Comment by dhruva205** [comment] 2019-06-06 04:50
> I couldn't tell

I inspected and found.. duplicating a slide makes 2 pages with the same id.. having same id of pages causes that story load time problem

**Comment by westonruter** [comment] 2019-06-06 06:18
The problem of duplicating a story page is a different issue that is captured in #2510.  So I guess this can be considered a duplicate of that one.

**Comment by miina** [comment] 2019-06-24 17:36
Looks like the only open issue here is part of the editor being hidden, there is a related issue, will close this and we can continue investigating there.

Closing as duplicate of #2510 and to further investigate part of the editor being hidden within #2662.

cc @swissspidy

**Closed by miina** 2019-06-24 17:36 UTC
Labels: AMP Stories, Feedback, Sprint 9, [Type] Bug
