### ISSUE TITLE
Special handling for smileys

### ISSUE THREAD

**Issue by mjangda** [ampproject/amp-wp#204] opened 2016-02-18 22:28 UTC
If we have an image with the `wp-smiley` smiley class, it should probably display inline and have a forced size. Currently, it gets inferred as `layout=responsive`, which isn't great.

**Comment by westonruter** [comment] 2018-01-30 08:14
I'm having a hard time reproducing this issue. Smilies I add to post content get rendered as emoji, not images.

**Comment by westonruter** [comment] 2019-01-11 22:32
I'm able to re-produce this now. 

With this raw post content:

```html
<p>Image: <img class="emoji loaded" draggable="false" src="https://s.w.org/images/core/emoji/11/svg/1f642.svg" alt="🙂"></p>

<p>Character: 🙂</p>
```

In HTML non-AMP this gets rendered as:

![image](https://user-images.githubusercontent.com/134745/51062744-e611df80-15ac-11e9-9429-877374084195.png)

Note that the emoji character is being converted into an image by WordPress's emoji handling. In AMP this is disabled, so the character passes through as a character but the image is incorrectly rendered in AMP:

![image](https://user-images.githubusercontent.com/134745/51062759-f1fda180-15ac-11e9-908a-d1140ec3c7e8.png)

The underlying HTML is:

```html
<p>Image: <amp-img class="emoji loaded amp-wp-unknown-size amp-wp-unknown-width amp-wp-unknown-height amp-wp-enforced-sizes" draggable="false" src="https://s.w.org/images/core/emoji/11/svg/1f642.svg" alt="🙂" width="525" height="400" layout="intrinsic"></amp-img></p>

<p>Character: 🙂</p>
```

The problem turns out to be an issue with `FasterImage` and how it was modified in https://github.com/ampproject/amp-wp/pull/1150 to allow extracting pixel dimensions from SVG images. The problem is that it is attempting to read 1024 bytes of data from the image, but the [above SVG](https://s.w.org/images/core/emoji/11/svg/1f642.svg) is only 525 bytes long. This results in a `WillWashburn\Stream\StreamBufferTooSmallException` exception being thrown, and the image size failing to be obtained, and thus the fallback image size is being used (which is obviously too big).

**Comment by westonruter** [comment] 2019-01-11 22:32
The issue presumably happens when someone copies post content _from the frontend_ after the emoji characters have been replaced with images.

**Comment by westonruter** [comment] 2019-03-07 00:52
With an impending update to `FasterImage` which includes revamped SVG image parsing, the results are as follows:

## Before

![image](https://user-images.githubusercontent.com/134745/51063167-aa781500-15ae-11e9-88c6-fc29d262946a.png)

## After

![image](https://user-images.githubusercontent.com/134745/51063184-b663d700-15ae-11e9-8b8e-a77ff08286d8.png)

While this is way better, it is still not perfect. The SVG image has a viewbox of 36x36 so that is what is assigned as the `width` & `height` of the `amp-img`. Nevertheless, the emojis are supposed to be 16x16. Or rather, they are [supposed to be `1em` by `1em`](https://github.com/WordPress/wordpress-develop/blob/33caf61b8ba988da73c2e210309566f9fdb039be/src/wp-includes/formatting.php#L5350-L5351), so it should look like this:

![image](https://user-images.githubusercontent.com/134745/51063318-57529200-15af-11e9-9f5a-cda38d56cd89.png)

So to full fix the case of inline SVG emojis we potentially need to either replace the `img.emoji` back with the underlying character (which is found in the `alt` attribute). This would not be ideal because we'd miss out on the improvements that WordPress's emoji handling was introduced for.

A full fix seems to be two-fold:

* Make emoji SVG images get sizes at `1em` somehow. This is a challenge because `amp-img` doesn't allow `em` units.
* Make an AMP-compatible version of WordPress's emoji handling, by adding a sanitizer that does in PHP what core does in JS. In the AMP plugin we disable the emoji handling in AMP:

https://github.com/ampproject/amp-wp/blob/c92e129333a8518088a37d47594079b537121d70/includes/class-amp-theme-support.php#L766-L767

**Comment by westonruter** [comment] 2019-03-07 05:52
This has been partially fixed by https://github.com/ampproject/amp-wp/pull/1936 which updates `FasterImage` to include the fix from https://github.com/willwashburn/fasterimage/pull/14.

**Closed** 2019-05-21 22:35 UTC
Labels: [Type] Bug
