### ISSUE TITLE
Blocks "jumping" when resizing to minimum limits fast

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#3444] opened 2019-10-04 15:16 UTC
## Bug Description

When resizing a block (any block _except for_ Text block without amp-fit-text) to small quickly, it jumps.

## Expected Behaviour

Block should stay in place even when resizing quickly.

## Steps to reproduce

1. Add a block (e.g. Text / Image)
2. Resize the block to be quite tall.
3. Rotate the block a bit.
4. Use the top resizing handle and reduce the block's height quickly.
5. See the results.

## Screenshots

![Screen Recording 2019-10-03 at 17 07 27](https://user-images.githubusercontent.com/637548/66164382-907cd780-e600-11e9-88b2-87b9cca1b31f.gif)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* AC1: When a block is placed on a page, regardless of size or rotational orientation, it should have a centered focal point, so when the block is rotated, or resized, it does not "jump" visually on the page.

Related to #3461 

## Implementation brief

Fixed in #3529. 

## QA testing instructions

1. Add a block (e.g. Text / Image)
1. Resize the block to be quite tall.
1. Rotate the block a bit.
1. Use the top resizing handle and reduce the block's height quickly.
1. Block should not move / jump. 

## Demo

* 

![junmping2](https://user-images.githubusercontent.com/3294597/67093306-9dc5c480-f1b1-11e9-8b8a-e334e8ad8c07.gif)
![jumping](https://user-images.githubusercontent.com/3294597/67093308-9dc5c480-f1b1-11e9-999d-eeefcc2b3426.gif)

## Changelog entry

*

**Comment by spacedmonkey** [comment] 2019-10-10 16:43
Looking into this issue, seems a little a simple fix to apply CSS fix. I found a property called [object-position](https://css-tricks.com/almanac/properties/o/object-position/).
```
.wp-block-image .components-resizable-box__container img {
       object-position: 50% 50%;
}
```

**Comment by miina** [comment] 2019-10-10 17:10
Note that this issue occurs with other blocks as well, at least with the Text block and Meta blocks.

**Comment by spacedmonkey** [comment] 2019-10-10 17:34
The calculation for top  is incorrect because of the angel and min height being met. Not sure why this is yet, I am going to continue to look into this.

**Comment by miina** [comment] 2019-10-14 12:24
@spacedmonkey FYI: here is the original comment based on which the issue was created if that's helpful somehow: https://github.com/ampproject/amp-wp/pull/3433#issuecomment-538130369

**Comment by spacedmonkey** [comment] 2019-10-14 16:52
I spent some more on this ticket. 

- The issue still happens even block is not rotated. 
- The issue only happens when the top resizer is used. 
- It only happens when the resize is done quickly.
- It only happens the moves goes pass the top edge of the element. (This the makes the bottom value a minus). 
- This issue is related to min height.

I have already spent most of the day into this. Should I look into this more @MackenzieHartung ? 

I think we need to look into the UX of what happens when a box resizes from the top to below bottom of the element. In google slides, the box, rotates itself once you size goes below the bottom edge.

https://youtu.be/EMLRo-B8pGY

Thoughts @cathibosco

**Comment by MackenzieHartung** [comment] 2019-10-14 21:46
@spacedmonkey do you have an idea of how much longer you would need to look into this?

**Comment by spacedmonkey** [comment] 2019-10-15 09:43
@MackenzieHartung No I don't. I have already spent around 8 hours on this issue. I know when the issue happens and why but don't have a fix. I also have a question around what should happen once the mouse is dragged before the top edge of a block. I have cited an example google slides for a possible expected behavior.

As I am stuck, maybe the next step would be jump on a call to discuss the issue. Maybe another brain on this will unblock it.

**Comment by spacedmonkey** [comment] 2019-10-15 12:38
Inspired by [this](https://github.com/ampproject/amp-wp/compare/fix/3458-smooth-snaplines?expand=1), I tried to implement `debounce` to slow down the drag. With no success.

**Comment by barklund** [comment] 2019-10-15 13:54
I suggest postponing this until later and re-visiting it while tackling the larger issue of switching to a "proven" best-practice component for all our resizing and dragging needs as discussed on slack. We've been monkey-patching the Gutenberg version for too long with no end in sight - let's switch to something that works. It's a larger task, but will reduce complexity and in particular tech debt.

**Comment by spacedmonkey** [comment] 2019-10-15 16:04
@MackenzieHartung I have moved this to revisit later, as all developers agree that this is a larger issue.

**Comment by miina** [comment] 2019-10-15 17:04
Just realized there might be some redundant logic in resizing which might be the cause of this issue. Will try to remove this within #3461 since I'm doing some changes there anyway to see if that helps, hopefully it works 🤞

**Comment by spacedmonkey** [comment] 2019-10-17 16:50
Moved to QA, added testing instructions and assigned to @csossi  .

**Comment by csossi** [comment] 2019-10-17 17:42
Verified in QA

**Closed** 2019-10-18 12:15 UTC
Labels: AMP Stories, Type: Bug, UX
