### ISSUE TITLE
When previewing a story most pages are empty (white background only), or have minimal text blocks in incorrect locations.

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#2686] opened 2019-06-26 09:18 UTC
In Chrome, created the provided story, upon selecting "preview" all pages displayed, basically, empty. Same thing happened in Publish.

I cannot reproduce this in Safari.

<img width="961" alt="Screen Shot 2019-06-26 at 5 17 57 AM" src="https://user-images.githubusercontent.com/24547817/60167804-d04a4c80-97d1-11e9-867f-8d120237d7da.png">

**Comment by westonruter** [comment] 2019-06-26 09:36
Are you logged-in as a user with an Author role?

**Comment by swissspidy** [comment] 2019-06-26 13:33
If it has to do with the role, this might be a duplicate of #2685.

**Comment by miina** [comment] 2019-06-26 16:06
Just tested and it seems to occur with Author role. Closing as duplicate of #2685.

**Closed by miina** 2019-06-26 16:06 UTC
Labels: AMP Stories, [Type] Bug
