### ISSUE TITLE
Text Presets

### ISSUE THREAD

**Issue by jauyong** [ampproject/amp-wp#3858] opened 2019-11-30 21:02 UTC
## Feature description

Text presets from templates and user generated are added to the Text Block library

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pbakaus** [comment] 2020-01-03 20:00
Duplicate of ampproject/web-stories-wp#29

**Closed by pbakaus** 2020-01-03 20:00 UTC
Labels: P0, Stories
