### ISSUE TITLE
Spacing Prob When Reducing Text Block Width

### ISSUE THREAD

**Issue by csossi** [ampproject/amp-wp#2615] opened 2019-06-13 00:36 UTC
Seeing a spacing problem in the editor

Started with this (auto-fit on):
![image](https://user-images.githubusercontent.com/16945664/59395318-533ec200-8d51-11e9-8ca2-c8e6898deab4.png)

Reduced the width slightly and it changed to this:
![image](https://user-images.githubusercontent.com/16945664/59395354-7ec1ac80-8d51-11e9-9925-12db94df7270.png)

**Comment by swissspidy** [comment] 2019-06-13 09:41
Moving to the 1.2 milestone for consideration. But I think it's enough of an edge case to tackle it in 1.2.1

**Comment by miina** [comment] 2019-06-13 14:52
@swissspidy Not sure why this happens at this moment. I just removed my assignment since I'm going offline for a few hours, unless you or @kienstra know a solution for that then we can probably leave it for 1.2.1.

**Comment by miina** [comment] 2019-06-17 15:52
I'm not able to reproduce this issue anymore, it's possible that the resizing changes had an influence on this too. @kienstra / @swissspidy Would you mind testing if you can still reproduce the issue?

**Comment by kienstra** [comment] 2019-06-19 02:01
**Couldn't Reproduce This**

Hi @miina,
Sorry for the delay.

The only case where I saw this issue was before the resizing ended, but that's probably not much of a problem.

![resizing-here](https://user-images.githubusercontent.com/4063887/59731517-b98e7d80-9246-11e9-8eaa-dfad7aa29496.gif)

**Comment by miina** [comment] 2019-06-19 12:13
Thanks for testing, @kienstra. I'm closing this as it seems it got resolved within other bug fixes.

**Closed by miina** 2019-06-19 12:13 UTC
Labels: AMP Stories, [AMP Stories] Editing Features, [Priority] Low, [Type] Bug
