### ISSUE TITLE
Issue when unexpected error occurs

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#2305] opened 2019-05-14 14:44 UTC
1. Within editing I was redirected to an error screen with the below message:

<img width="1244" alt="Unexpected Error" src="https://user-images.githubusercontent.com/24547817/57707019-e1ca0180-7634-11e9-859b-c4387d6d1c33.png">

2. I chose to "attempt recovery", and upon selection was taken back to the editor with this view:
<img width="1261" alt="Recovery screen" src="https://user-images.githubusercontent.com/24547817/57707057-f3130e00-7634-11e9-89e1-0d637a0ed329.png">

3. I refreshed, and the page returned to normal/ as expected:
<img width="1262" alt="Refresh" src="https://user-images.githubusercontent.com/24547817/57707094-01f9c080-7635-11e9-93d0-34ad0a1bd9d9.png">

In discussions with @miina this is possibly related to Issue #2253

**Comment by swissspidy** [comment] 2019-05-14 18:00
@MackenzieHartung Is there any chance you could reproduce this and then check the error messages in the developer tools (open using F12) when the issue happens again. A screenshot of these errors and clear steps to reproduce would be tremendously helpful.

**Comment by miina** [comment] 2019-05-29 12:15
Closing this as it's almost certain that the error was due to the same issue as in #2253 and got fixed.


@swissspidy Let me know if you'd like to look into this more.

**Closed by miina** 2019-05-29 12:15 UTC
Labels: AMP-Stories, [Type] Bug
