### ISSUE TITLE
Preview misses content

### ISSUE THREAD

**Issue by amedina** [ampproject/amp-wp#2217] opened 2019-04-29 23:41 UTC
Creating a story and after adding the fourth page, the preview did not show it (see screencast)
![Screen Shot 2019-04-29 at 4 41 25 PM](https://user-images.githubusercontent.com/506089/56933645-aa3c5080-6a9d-11e9-9d21-5f5c0667b50a.png)
![Screen Shot 2019-04-29 at 4 41 32 PM](https://user-images.githubusercontent.com/506089/56933653-af999b00-6a9d-11e9-9198-418808938d77.png)

**Comment by westonruter** [comment] 2019-04-29 23:45
@amedina even with hard reload? This may be unrelated to AMP Stories, and it may be a duplicate of #1731.

**Comment by swissspidy** [comment] 2019-05-10 18:31
I am unable to reproduce this right now.

I know that in the past there have been reports upstream in the Gutenberg repository about changes not always being reflected, however that was usually because users did not save their changes or they did not refresh.

Agreed that it sounds like a duplicate of #1731 too.

**Comment by swissspidy** [comment] 2019-05-10 23:44
Closing as unconfirmed potential duplicate.

**Closed by swissspidy** 2019-05-10 23:44 UTC
Labels: AMP-Stories, [Type] Bug, duplicate
