### ISSUE TITLE
Image Not Rendering Properly on Mobile and Desktop

### ISSUE THREAD

**Issue by MackenzieHartung** [ampproject/amp-wp#3429] opened 2019-10-03 10:15 UTC
## Bug Description

The image entered during editing renders differently (erroneously) once published.

## Expected Behaviour

Story should visually look the same in the editor and once published.

## Steps to reproduce

1. Add image block to page
2. Preview/Publish
3. Image block displays incorrectly

## Screenshots

<img width="464" alt="Screen Shot 2019-10-03 at 6 14 10 AM" src="https://user-images.githubusercontent.com/24547817/66118711-12d7ae00-e5a5-11e9-99aa-0918f4485366.png">

<img width="446" alt="Screen Shot 2019-10-03 at 6 14 17 AM" src="https://user-images.githubusercontent.com/24547817/66118716-153a0800-e5a5-11e9-863d-48b5f859d57a.png">

## Additional context

 - WordPress version:
 - Plugin version: 1.3-rc
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* AC1: When creating stories in the editor, image within image blocks should display the same in the preview/publish view.

## Implementation brief

* The issue of 0% displaying as 5% comes from PHP where `empty` gives positive value for `0`, this causes using the default `5` as the value:
On 0% being displayed as 5%: yep, `5` is indeed the default value for `positionLeft`. Looks like the issue comes from PHP where `0` is considered `empty` :
https://github.com/ampproject/amp-wp/blob/5799032d4cc9882ceac94966f67c318ebb60eb68/includes/class-amp-story-post-type.php#L1534

We should replace using `empty` by something more reliable, perhaps with `isset` or strict equals for `0`.

* The weird displaying of images due to `display:table` can be fixed by overriding the value in the plugin's `amp-stories-frontend.css` file for `.wp-block-image.is-resized` and other `.wp-block-image.*` values. See `/gutenberg/packages/block-library/src/image/style.scss` to check where the `display:table` is set. The value should be `display: block` instead.

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by spacedmonkey** [comment] 2019-10-14 11:05
I believe this issue is related to the calculations to get font size based on text box size being different from the stories editor compared the AMP stories front end. I believe it is going to hard to each calculations to exactly match.

**Comment by barklund** [comment] 2019-10-15 19:23
The text is placed exactly like in the editor. It's the image that's completely off.

These are the screenshots next to each other with some guides on top:

<img width="930" alt="Screenshot 2019-10-15 at 15 22 03" src="https://user-images.githubusercontent.com/637548/66862783-9f984980-ef5f-11e9-8f35-de9c4496282b.png">

**Comment by jauyong** [comment] 2019-10-16 12:44
@barklund I've updated the ticket to indicate the issue is regarding the image, not text.

**Comment by spacedmonkey** [comment] 2019-10-16 16:56
Possibly related https://github.com/ampproject/amp-wp/issues/3498

**Comment by barklund** [comment] 2019-10-16 20:53
### Problem 1

If you place an item directly on the left edge, exactly at `left: 0%´, in the resulting story it is placed at `left: 5%`.

I guess it's a default somewhere, but 0 here is not a lack of coordinate, it's specifically 0 and should be respected.

### Problem 2

The display model for the `<figure>` containing a placed image is set to `table`, which can render it very weirdly, often rendering it at a wrong height. Simply disabling this line of CSS and then re-enabling it, fixes the image layout. Setting it to `display:block` of course also fixes it.

Why is it set to `table` and where does it come from? I've tracked it to this inline style in the HTML (line 3 in the screenshot), but I can't find any `amp-custom.css` anywhere, so I have no idea who has defined this:

<img width="392" alt="Screenshot 2019-10-16 at 16 50 05" src="https://user-images.githubusercontent.com/637548/66957919-1f441800-f035-11e9-9ba7-c963e4a1ead0.png">

It's present both in my local install and in the Pantheon-site, so it must be defined in the plugin and not as some custom setting (it could also be the 2019 theme, but that seems less likely). I have no idea where it's defined nor why.

### Example for both

| In Editor |
| -- |
| <img width="400" alt="Screenshot 2019-10-16 at 16 31 33" src="https://user-images.githubusercontent.com/637548/66956488-772d4f80-f032-11e9-91ef-767b77bfbcb8.png"> |
| _[An image has been placed in the upper left corner of the page at 0,0 taking up (as well as possible) exactly 25% of the entire page (link to Pantheonsite).](https://story-test-wordpress-amp.pantheonsite.io/wp-admin/post.php?post=3971&action=edit)_ |

| In Story |
| - |
| <img width="681" alt="Screenshot 2019-10-16 at 16 31 39" src="https://user-images.githubusercontent.com/637548/66956702-ddb26d80-f032-11e9-94d5-4d8ee1b7af6b.png"> |
| _[Here, the image is clearly not placed in the corner, and the height is way off (the width is correct).](https://story-test-wordpress-amp.pantheonsite.io/?post_type=amp_story&p=3971&preview=true)_ |

### Conclusion

I really don't know where to fix either issue.

Thoughts for fixing either, @miina, @swissspidy, @spacedmonkey?

**Comment by swissspidy** [comment] 2019-10-16 21:24
IIRC the table layout is defined by the Gutenberg block library CSS. We could override that.

amp-custom is an artificial name as the AMP plugin gathers all CSS used on a page and puts it into that inline style tag.

**Comment by miina** [comment] 2019-10-17 10:00
Thanks for looking into this issue!

On 0% being displayed as 5%: yep, `5` is indeed the default value for `positionLeft`. Looks like the issue comes from PHP where `0` is considered `empty` :
https://github.com/ampproject/amp-wp/blob/5799032d4cc9882ceac94966f67c318ebb60eb68/includes/class-amp-story-post-type.php#L1534

On the CSS:
- AMP [doesn't allow external stylesheets](https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages/) on AMP Pages and thus the plugin processes all the stylesheets applied to the page, removes the disallowed and unused CSS rules, and then puts it all together to display in allowed format (`<style amp-custom>`).
- Looks like the `display:table` comes from `/gutenberg/packages/block-library/src/image/style.scss` file, if I understand correctly. We could override this in our plugin.

**Comment by miina** [comment] 2019-10-17 10:06
> Just to clarify, it sounds like overriding display:table and changing the empty check to something else might be all that's needed?

Yes, looks like it.

**Comment by miina** [comment] 2019-10-17 16:42
Moved to IBR!

**Comment by spacedmonkey** [comment] 2019-10-17 16:46
Approved IBR.

**Comment by barklund** [comment] 2019-10-17 16:46
Looks good to me. Let's get this executed.

However, do remember to do a `git blame` on that `display:table` to check with whomever did the original code to ensure, that we don't screw up something else.

**Comment by miina** [comment] 2019-10-17 16:50
Note that `display: table` comes from the Gutenberg (upstream) plugin and not from the AMP Plugin. AMP Plugin combines _all the_ CSS, from other plugins as well, to make it valid for an AMP Page, that's why it shows up in the `amp-custom.css` (the dynamically created CSS).

**Comment by spacedmonkey** [comment] 2019-10-17 16:53
@miina This seems like a S to me. As it seems you have basically done the work.

**Comment by miina** [comment] 2019-10-17 16:55
Sounds good, moving to Todo!

**Closed** 2019-10-18 13:51 UTC
Labels: AMP Stories, Size: S, Type: Bug

**Comment by csossi** [comment] 2019-10-18 17:11
Verified in QA
