### ISSUE TITLE
Consider adding resize handles to left and top edges of the blocks

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2410] opened 2019-05-24 12:01 UTC
Once the block mover has been completely removed, dragging can be done by dragging the element itself, and there are no other handles, we could add a resize handle to every side.

Right now it's only possible to resize from the bottom and right size which is not the best user experience in case of rotated blocks.

**Comment by swissspidy** [comment] 2019-05-24 15:53
Corners would be nice too in order to easily change both width and height.

**Comment by swissspidy** [comment] 2019-09-27 09:39
Duplicate of #2985 which was fixed in 1.3.

**Closed by swissspidy** 2019-09-27 09:39 UTC
Labels: AMP Stories, Status: Duplicate, Type: Enhancement
