### ISSUE TITLE
catalog amp story in posts and switch between them

### ISSUE THREAD

**Issue by Amanrazdan** [ampproject/amp-wp#2440] opened 2019-05-28 06:35 UTC
Is it possible to list stories like post and add tags and categories to it. I Tried changing the post type slug in class-amp-story-post-type.php from story to posts which overrides wordpress default posts and create everything as fine as story but then again i couldnt't create a post. Is thier a way to let them coexist on the same platform `class AMP_Story_Post_Type {

	/**
	 * The slug of the post type to store URLs that have AMP errors.
	 *
	 * @var string
	 */
	// to make stories behave like posts
	const POST_TYPE_SLUG = 'post';

	/**
	 * The image size for the AMP story card, used in an embed and the Latest Stories block.
	 *
	 * @var string
	 */
	const STORY_CARD_IMAGE_SIZE = 'amp-story-poster-portrait';

	/**
	 * The image size for the poster-landscape-src.
	 *
	 * @var string
	 */
	const STORY_LANDSCAPE_IMAGE_SIZE = 'amp-story-poster-landscape';

	/**
	 * The image size for the poster-square-src.
	 *
	 * @var string
	 */
	const STORY_SQUARE_IMAGE_SIZE = 'amp-story-poster-square';

	/**
	 * The large dimension of the AMP Story poster images.
	 *
	 * @var int
	 */
	const STORY_LARGE_IMAGE_DIMENSION = 928;

	/**
	 * The small dimension of the AMP Story poster images.
	 *
	 * @var int
	 */
	const STORY_SMALL_IMAGE_DIMENSION = 696;

	/**
	 * The slug of the story card CSS file.
	 *
	 * @var string
	 */
	const STORY_CARD_CSS_SLUG = 'amp-story-card';

	/**
	 * The rewrite slug for this post type.
	 *
	 * @var string
	 */
	const REWRITE_SLUG = 'posts';

	/**
	 * AMP Stories style handle.
	 *
	 * @var string
	 */
	const AMP_STORIES_STYLE_HANDLE = 'amp-story-style';

	/**
	 * Check if the required version of block capabilities available.
	 *
	 * @return bool Whether capabilities are available.
	 */
	public static function has_required_block_capabilities() {
		if ( ! function_exists( 'register_block_type' ) ) {
			return false;
		}

		// TODO: Require only the latest WordPress version itself, not the plugin.
		return function_exists( 'gutenberg_pre_init' );
	}
`

**Comment by Amanrazdan** [comment] 2019-05-28 06:36
![image](https://user-images.githubusercontent.com/28403318/58456121-f59b5a80-8140-11e9-8722-f68bcd1b93df.png)
![image](https://user-images.githubusercontent.com/28403318/58456151-0ea40b80-8141-11e9-9422-e86379e9943b.png)

**Comment by Amanrazdan** [comment] 2019-05-28 07:41
what if we can add an option to choose story in pst format side option that opens stories editor

![image](https://user-images.githubusercontent.com/28403318/58459864-fbe20480-8149-11e9-8a4d-7a67042b3453.png)

**Comment by westonruter** [comment] 2019-05-28 16:04
Is this a duplicate of #2439?

**Comment by swissspidy** [comment] 2019-05-28 16:13
Thanks for your report @Amanrazdan. It indeed looks like #2439 covers adding a taxonomy for stories.

As for your post formats suggestion, I believe it's a very interesting one. However, I think it's not feasible due to technical limitations surrounding post formats and the requirements we have for implementing the stories editor. The stories editor will probably only diverge more and more from Gutenberg in the future, so we want to have a clear distinction there. This way also ensures a consistently great user experience.

**Comment by swissspidy** [comment] 2019-05-28 16:14
With that being said, please follow #2439 for updates 🙂

**Closed by swissspidy** 2019-05-28 16:14 UTC
Labels: AMP-Stories, duplicate

**Comment by Amanrazdan** [comment] 2019-05-28 17:26
Thanks
