### ISSUE TITLE
[AMP Stories] Possible Recursion Bug (Maximum call stack size exceeded)

### ISSUE THREAD

**Issue by miina** [ampproject/amp-wp#2064] opened 2019-04-04 12:40 UTC
Steps to reproduce:
- Add a Page;
- Set a background image with focal point;
- Set background color;
- Click save.

![Screen Shot 2019-04-04 at 2 39 42 PM](https://user-images.githubusercontent.com/3294597/55556304-8593c980-56e7-11e9-8457-b800891b2218.png)

**Comment by swissspidy** [comment] 2019-04-04 12:43
Thanks for testing this!

In my quick test this also happened without explicitly changing the focal point and without setting a background _color_.

In the debug trace `isBeingScheduled` from Gutenberg is being mentioned, so maybe it has to do with wrong date formats or something. This is best investigated on a local install with a development version of Gutenberg.

**Comment by westonruter** [comment] 2019-04-04 21:47
I noticed this happening as well when just dragging an image block in a page:

![image](https://user-images.githubusercontent.com/134745/55590432-bd027600-56e7-11e9-9be1-ed714fddcc24.png)

Relatedly I saw this when adding text to a Text block:

![image](https://user-images.githubusercontent.com/134745/55590635-49ad3400-56e8-11e9-9fd8-8069c76e9e23.png)

These errors are difficult to reproduce, however 😦

**Comment by westonruter** [comment] 2019-04-05 17:35
It also happened to me right when selecting a background image, even without changing the focal point:

![image](https://user-images.githubusercontent.com/134745/55645860-8df30f80-578e-11e9-9294-c161e5a761b3.png)

**Comment by westonruter** [comment] 2019-04-05 17:39
I also noticed it when saving a draft after setting the featured image:

![image](https://user-images.githubusercontent.com/134745/55646053-035ee000-578f-11e9-9ba7-f170e81ed8cb.png)

**Comment by swissspidy** [comment] 2019-04-05 22:58
Interesting. I wonder if it has anything to do with how we are using the data store. I might find out more tomorrow at Zac Gordon‘s talk about that topic at the WordCamp.

**Comment by miina** [comment] 2019-04-08 22:23
@swissspidy Did you find anything out meanwhile? Not sure if it's related but could be related with data store is that at this moment going to a Saved page the "Update" button is active, it looks like something is changed in the state without the user doing anything.

I remember that something similar happened previously and you reworked something in the store to fix it.

Might not be related at all though.

**Comment by swissspidy** [comment] 2019-04-10 09:40
I had put it aside for a bit to work on other issues. While I found some room for improvement in the way we subscribe to things, I am no unable to reproduce the max call stack size issue specifically. Very odd. Maybe a Gutenberg update changed something or so?

Still want to fix the _going to a Saved page the "Update" button is active_ part though.

**Comment by swissspidy** [comment] 2019-04-11 13:28
So I _sometimes_ get the issue with #2097 when inserting the "Story Date" block. When it happens, the editor crashes immediately when inserting the block. I cannot even open the editor in a new tab again after that because of the infinite loop.

Other times, it works without problems.

That block basically does `wp.date.dateI18n( wp.date.__experimentalGetSettings().formats.date, wp.data.select( 'core/editor' ).getEditedPostAttribute('date') )`, which uses Moment.js under the hood.

Given that the original report also references Moment, there seems to be some incompatibility there.

I have yet to find the common underlying issue though.

**Comment by swissspidy** [comment] 2019-04-12 12:20
Today it happened when inserting an image block without doing anything else after that:

![Screenshot 2019-04-12 at 12 37 51](https://user-images.githubusercontent.com/841956/56036825-23157b80-5d2e-11e9-96f6-a1e496020a36.png)

**Comment by miina** [comment] 2019-04-22 17:49
Note: started looking into this issue to find the cause.

**Comment by westonruter** [comment] 2019-04-24 23:27
Closing due to merging #2173.

**Closed by westonruter** 2019-04-24 23:27 UTC
Labels: AMP-Stories, Sprint 4, [AMP-Stories] Editing features, [Type] Bug
