### ISSUE TITLE
Enhance UX for adding poster images

### ISSUE THREAD

**Issue by amedina** [ampproject/amp-wp#2223] opened 2019-04-30 15:52 UTC
At the moment if a poster image is not provided for a video, an AMP validation error is triggered. Not clear for users what is happening. Since users should not ever see validation errors, we should automate its population if possible, or notify the user otherwise. 

Something like this is done already for feature images.

**Comment by westonruter** [comment] 2019-04-30 16:07
Ideally the default poster would be automatically extracted from the video: https://github.com/ampproject/amp-wp/issues/903

**Comment by westonruter** [comment] 2019-04-30 23:29
This could be considered a duplicate of #2109.

**Comment by westonruter** [comment] 2019-06-05 02:20
Closing as duplicate.

**Closed by westonruter** 2019-06-05 02:20 UTC
Labels: AMP-Stories, duplicate
